In [1]:
import numpy as np

# The Basics

In [3]:
a = np.array([1,2,3]) #1D Array
a

array([1, 2, 3])

In [5]:
b = np.array([[9.0,8,7],[6.0,5,4]]) #2D Array
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
#Get Dimension
#a.ndim
b.ndim

2

In [8]:
#Get Shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

## Accessing rows and columns and specific elements

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [11]:
#Get a specific element : nparray[r, c]

a[1,5] #prints 13

13

In [12]:
a[1,-2] #negative indexing 

13

In [13]:
#Get a specific row 
a[0,:] #first row all columns

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
a[0] #Another method for first row all columns

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#Get a specific column
a[:,2] #3rd column

array([ 3, 10])

In [16]:
#Getting a little fancy : nparray[startindex:endindex:stepsize]
a[1:6:2]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
a[0,1:6:2]

array([2, 4, 6])

## Initializing Different Types of Arrays

In [18]:
# All 0s matrix 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#All 1s matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
#Any other number
np.full((2,2),5)

array([[5, 5],
       [5, 5]])